seed: 42
work_dir: /home/user/project/work_dir
resume_from: null
dist:
  backend: nccl
  world_size: 4
  init_method: env://
amp:
  enabled: true
  opt_level: O1
workflow:
  - { phase: train, iters: 100 }
  - { phase: val,   iters: 10 }
  - { phase: test,  iters: 1 }
total_epochs: 20
hooks:
  logger:
    type: LoggerHook
    interval: 20
  checkpoint:
    type: CheckpointHook
    interval: 1
  resume:
    type: ResumeHook
    enable: true
  lr_scheduler:
    type: LrSchedulerHook
    scheduler:
      # 这里填写用的 PyTorch scheduler 名称及参数，
      # 也可以写完整路径指向自定义 scheduler
      type: StepLR
      step_size: 10
      gamma: 0.5
  ddp:
    type: DDPHook
  amp:
    type: AMPHook
  tensorboard:
    type: TensorboardHook
  wandb:
    type: WandbHook
    init_args:
      project: my_project
      name: ${experiment_name}
      mode: disabled
data:
  train:
    type: ClassificationImageDataset
    annotation_file: /mnt/volumes/vc-profile-bd-ga/others/wubo/Projects/Data/006/Cabin/ClothingIndex/annos/train.jsonl
    x_key: image_path
    y_key: category_id
  val:
    type: ClassificationImageDataset
    annotation_file: /mnt/volumes/vc-profile-bd-ga/others/wubo/Projects/Data/006/Cabin/ClothingIndex/annos/val.jsonl
    x_key: image_path
    y_key: category_id
  # test:
  #   type: ClassificationImageDataset
  #   data_path: /path/to/test
  train_dataloader:
    batch_size: 32
    shuffle: true
  val_dataloader:
    batch_size: 32
    shuffle: false
  # test_dataloader:
  #   batch_size: 32
  #   shuffle: false
model:
  type: resnet50
  num_classes: 12
  # pretrained: false
optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001
lr_scheduler:
  type: StepLR
  step_size: 10
  gamma: 0.5