seed: 42
work_dir: /home/user/project/work_dir
resume_from: null
dist:
  backend: nccl
  world_size: 4
  init_method: env://
amp:
  enabled: true
  opt_level: O1
workflow:
  - { phase: train, iters: 100 } # 如果设置了 iters 则表示每个epoch 总共 100 iters，否则按照 samples num 和 batch size 计算
  - { phase: val }
  # - { phase: test }
total_epochs: 20
hooks:
  metrics:
    type: MetricHook
    top1:
      type: "Accuracy"
      topk: 1
    top5:
      type: "Accuracy"
      topk: 5
  checkpoint:
    type: CheckpointHook
    interval: 1
  resume:
    type: ResumeHook
    enable: true
  lr_scheduler:
    type: LrSchedulerHook
    scheduler:
      # 这里填写用的 PyTorch scheduler 名称及参数，
      # 也可以写完整路径指向自定义 scheduler
      type: StepLR
      step_size: 10
      gamma: 0.5
  logger:
    type: LoggerHook
    interval: 1
    log_dir: ${work_dir}/logs
    log_items:
      # 从 wf.optimizer.param_groups[0]['lr'] 里取 lr
      lr: "optimizer.param_groups.0.lr"
      # 从 wf.meters 这个字典里取 top1
      top1: "meters['top1'].avg"
      # 也可以直接写成 callable，但 yaml 里不能序列化函数，
      # 如果想用 callable，则需要在代码里替换或动态注入
  ddp:
    type: DDPHook
  amp:
    type: AMPHook
  tensorboard:
    type: TensorboardHook
  wandb:
    type: WandbHook
    init_args:
      project: my_project
      name: ${experiment_name}
      mode: disabled
data:
  train:
    type: ClassificationImageDataset
    annotation_file: train.jsonl
    x_key: image_path
    y_key: category_id
  val:
    type: ClassificationImageDataset
    annotation_file: val.jsonl
    x_key: image_path
    y_key: category_id
  # test:
  #   type: ClassificationImageDataset
  #   data_path: /path/to/test
  train_dataloader:
    batch_size: 8
    shuffle: true
  val_dataloader:
    batch_size: 8
    shuffle: false
  # test_dataloader:
  #   batch_size: 8
  #   shuffle: false
model:
  type: resnet50
  num_classes: 12
  # pretrained: false
optimizer:
  type: Adam
  lr: 0.001
  weight_decay: 0.0001
lr_scheduler:
  type: StepLR
  step_size: 10
  gamma: 0.5